### ISSUE TITLE
intall command

### ISSUE THREAD

**Issue by aghili371** [converge/instapy-dashboard#1]
how i can run the install command? please give me more information

**Comment by timgrossmann** [comment]
`npm install` 😉

**Comment by aghili371** [comment]
unfortunately, it doesn't work for me,

E:\instapy-dashboard-master>yarn install
'yarn' is not recognized as an internal or external command,
operable program or batch file.

**Comment by converge** [comment]
hey guys, just updated it, it should work now.

*have a look on the docs.
