### ISSUE TITLE
Where does all data stored?

### ISSUE THREAD

**Issue by dlenskyi** [converge/instapy-dashboard#17]
I'm not so strong in JS, and I don't know where all the data stored. And is it really stored? Or instapy-dashboard just takes live data from InstaPy folder and shows it?

**Comment by converge** [comment]
InstaPy is storing it for us, we're just collecting it from log files and database.

We just need to set the InstaPy folder following the setup(readme.md). are you able to load it?

**Comment by dlenskyi** [comment]
Yep, All is fine ;) okay, I got it !
Thanks so much for this feature by the way!)
