### ISSUE TITLE
Multiple Accounts and Databases

### ISSUE THREAD

**Issue by flashguy22** [converge/instapy-dashboard#20]
I enabled separate databases for my accounts because I was getting lock errors.

`Settings.database_location = "./db/instapy_{}.db".format('account1')`

Now the UI doesn't update as it still reads the values from the old database.

Is there a way to get this working again?

**Comment by converge** [comment]
Hey @flashguy22 ,

the Dashboard will look for just one database (the default one in the InstaPy database path).

**Comment by flashguy22** [comment]
Ok, got it. Thanks for getting back.

How about we make this a feature request to add multiple databases in the config file?

**Comment by converge** [comment]
I believe isn't the best option, because we would be creating a workaround for the InstaPy issue, the best option is to fix InstaPy issue and we will have everything working.

I saw that there is a PR to move InstaPy from SQLite to MongoDB, it will fix the issue for sure.

**Comment by flashguy22** [comment]
Ok, great. I will need to wait for that update then to use your great dashboard. Currently running 3 accounts on a raspberry pi 3b+ and with one db it always crashes..

**Comment by CharlesCCC** [comment]
I'm facing similar issue when running multiple account , the sqlite get locked up. 
I guess, one way to have the Dashboard support with `Settings.database_location = "./db/instapy_{}.db".format('account1')` is do sometihing similar in the `routes.js` to accept a parameter with the username `account1` ...

**Comment by converge** [comment]
As it's something that required changes on InstaPy core, I'm closing it.

**Comment by ishandutta2007** [comment]
@converge this is not an issue with instapy core, this is a feature that was introduced by @CharlesCCC recently(probably after your work on instapy-dashboard). Migrating to mongo db is a different thing as split-db flag was written not to prevent lock but as the core instapy entire app's logics was written to handle only one account, so it was mixing up data of the multiple accounts which impacts restriction logics of one account on the other.  @CharlesCCC correct me if I am wrong.

**Comment by CharlesCCC** [comment]
@ishandutta2007 I think @converge means the underlying change will require InstaPy core change.

but I agree with you @ishandutta2007 , have Dashboard support multiple sqlite db shouldn't too hard, as long as the dashboard support multiple user accounts, then just passing different sqlite db name to each user's dashboard. 

`UserA.db` --> UserA

`UserB.db`  --> UserB
