### ISSUE TITLE
Not working with multiples DB

### ISSUE THREAD

**Issue by danenco** [converge/instapy-dashboard#22]
Last InstaPy update broke project

**Comment by danenco** [comment]
I'm facing similar issue when running multiple account , the sqlite get locked up. 
I guess, one way to have the Dashboard support with `Settings.database_location = "./db/instapy_{}.db".format('account1')` is do sometihing similar in the `routes.js` to accept a parameter with the username `account1` ...

_Originally posted by @CharlesCCC in https://github.com/converge/instapy-dashboard/issues/20#issuecomment-479986379_

**Comment by converge** [comment]
Hey @danenco, this solution they found is a workaround, I won't reflect it for the dashboard. Maybe soon we will have a definitive solution and I can follow their changes for the dashboard.
