### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by andifds** [converge/instapy-dashboard#24]
I got the same problem (https://github.com/converge/instapy-dashboard/issues/14) on two separated installations on Linux.

One is Ubuntu on EC2 and another one is Raspberry on my local network.
Both of them shows nothing. Started InstaPy service, but nothing.

Checked my .env file and all is ok, the path directs to the current directory with db and logs folders.

**Comment by converge** [comment]
duplicated https://github.com/converge/instapy-dashboard/issues/14
