### ISSUE TITLE
Live logs doesn't work

### ISSUE THREAD

**Issue by Immelstorn** [converge/instapy-dashboard#25]
Hi, I have an issue with Live logs feature. Stats dashboard works fine, but live logs is loading forever and shows nothing. https://take.ms/8YJIQ

I'm running this on rPI if it matters and here is my .env file https://monosnap.com/file/1FRPAB3pPjFE4Fx7bLFaSn8h03YXMs

**Comment by converge** [comment]
seems like it's everything okay. In the DevTools, on Networks tab, do you see some 4xx or 5xx response?

**Comment by Immelstorn** [comment]
No, I don't. https://take.ms/yTOjRx

**Comment by danielpalmas** [comment]
I have the same problem. It does not update the dashboard. The problem started after setting "split_db". 

session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
		  split_db=True,
                  multi_logs=True)

**Comment by Immelstorn** [comment]
I do not have split_db set

**Comment by Immelstorn** [comment]
I guess it is some problem with websockets, they are forever pending in Network tab

**Comment by converge** [comment]
I never tried it on RPi, but something else that you can check is:
1. your InstaPy should be running at the moment
2. it should be writing logs in ```~/InstaPy/logs/ANY_USERNAME/general.log```

**Comment by Immelstorn** [comment]
Both are true: https://take.ms/NdGlU

The only "but" is Instapy is running, but it is sleeping right now. I thought I will see some of the last log entries on the log page in this case, won't I?

**Comment by danielpalmas** [comment]
I'm having problems when I set up "split_db", some solution to this problem? When setting up I only have updates from "Live Logs"

**Comment by danielpalmas** [comment]
This happened after the update, because of the database lock.

**Comment by Immelstorn** [comment]
Well, false alarm. It works, I just supposed it will show something when page is loaded, but no new log entries are pushed. I restarted script and logs are shown realtime.

@converge I guess it is a feature request now, can we have like 20 last log entries shown on page load?

**Comment by converge** [comment]
@danielpalmas the split_db is an InstaPy workaround, I'm not ok with this idea, and won't reflect it on the dashboard.

@Immelstorn good to know 🎉 . Thank you for the ideas, I'm marking this issue as feature request now.

**Comment by danielpalmas** [comment]
@converge The problem is that it does not have this configuration, it does not work more than one database at the same time. The database blocks and the script stops working.

**Comment by converge** [comment]
That's correct, but it's an InstaPy issue.

Em sex, 12 de abr de 2019 às 09:35, Daniel Souza <notifications@github.com>
escreveu:

**Comment by converge** [comment]
https://github.com/converge/instapy-dashboard/commit/8d3ce2d1ec42cb133b1d5faa1f91faead8311ddb
