### ISSUE TITLE
User statistics is broken

### ISSUE THREAD

**Issue by Immelstorn** [converge/instapy-dashboard#29]
Hi. It looks like User statistics is showing wrong numbers. If I had 1220 followers yesterday and 1233 today - it shows that I've lost 13, not gained. It just substracts numbers in the wrong order I guess.
Also, graph doesn't show negative numbers
Screenshot: https://take.ms/NaEaG

**Comment by converge** [comment]
Hey, thanks for that, just updated it to the old style: https://github.com/converge/instapy-dashboard/commit/4f55c103d0b413f28572f161b4eab0e31dd3bfb4

I'll reserve it again in the future with more tests.
