### ISSUE TITLE
Statistic is not working on a remote machine

### ISSUE THREAD

**Issue by fadriPi** [converge/instapy-dashboard#38]
the statistics is working well on the local machine. when I open the site from an machine in the same network, the site is shown up but the data couldn't load. 
![loading-statistics](https://user-images.githubusercontent.com/14263374/59011456-19435c80-8835-11e9-9028-5bccedd2780f.PNG)

In the documentation for the ".env"-file it says:

"if using only on localhost, keep it:"

but how can I change it when I will use it on other machines in the local network?

Thanks for your help.

**Comment by converge** [comment]
hey @fadriPi , have a look on this issues, it's kind similar;
https://github.com/converge/instapy-dashboard/issues/9

**Comment by fadriPi** [comment]
thanks a lot @converge ! missed that post.... now it works.
